import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import nextPlugin from '@next/eslint-plugin-next';
import reactPlugin from 'eslint-plugin-react';
import reactHooksPlugin from 'eslint-plugin-react-hooks';
import jsxA11yPlugin from 'eslint-plugin-jsx-a11y';
import eslintCommentsPlugin from '@eslint-community/eslint-plugin-eslint-comments/configs';
import prettierConfig from 'eslint-config-prettier';
import prettierPlugin from 'eslint-plugin-prettier';
import globals from 'globals';

export default tseslint.config(
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'coverage/**',
      'playwright-report/**',
      'playwright/.cache/**',
      'test-results/**',
      'next-env.d.ts',
      'out/**',
      '.vercel/**',
      'pnpm-lock.yaml',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,

  {
    ...reactPlugin.configs.flat.recommended,
    settings: { react: { version: 'detect' } },
  },
  reactPlugin.configs.flat['jsx-runtime'],

  {
    plugins: { 'react-hooks': reactHooksPlugin },
    rules: reactHooksPlugin.configs.recommended.rules,
  },

  jsxA11yPlugin.flatConfigs.recommended,

  {
    plugins: { '@next/next': nextPlugin },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs['core-web-vitals'].rules,
    },
  },

  eslintCommentsPlugin.recommended,

  {
    plugins: { prettier: prettierPlugin },
    rules: {
      'prettier/prettier': 'error',
    },
  },
  prettierConfig,

  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
      globals: { ...globals.browser, ...globals.node },
    },
    rules: {
      '@typescript-eslint/ban-ts-comment': [
        'error',
        {
          'ts-expect-error': 'allow-with-description',
          'ts-ignore': 'allow-with-description',
          'ts-nocheck': 'allow-with-description',
          'ts-check': false,
          minimumDescriptionLength: 10,
        },
      ],
      '@eslint-community/eslint-comments/require-description': [
        'error',
        { ignore: ['eslint-enable'] },
      ],
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      'no-debugger': 'error',
    },
  },

  /*
   * Repository boundary enforcement (S-1.10).
   *
   * Application code must go through `@/lib/db/repositories` so access
   * contracts (e.g., AuditLog immutability) are enforced at the type level
   * rather than being convention only. Direct imports of `@/lib/db/prisma`
   * are banned outside:
   *   - src/lib/db/**     : the client itself, extensions, repositories
   *   - prisma/**         : seeds and migration scripts
   */
  {
    files: ['src/**/*.{ts,tsx}'],
    ignores: ['src/lib/db/**'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: '@/lib/db/prisma',
              message:
                'Import from @/lib/db/repositories instead. Direct prisma access is restricted to src/lib/db/** to preserve AuditLog immutability and tenancy guarantees.',
            },
          ],
          patterns: [
            {
              group: ['**/lib/db/prisma', '**/lib/db/prisma.ts'],
              message:
                'Import from @/lib/db/repositories instead. Direct prisma access is restricted to src/lib/db/** to preserve AuditLog immutability and tenancy guarantees.',
            },
          ],
        },
      ],
    },
  },

  {
    files: ['**/*.{js,mjs,cjs}', 'eslint.config.mjs', 'next.config.ts', 'postcss.config.mjs'],
    ...tseslint.configs.disableTypeChecked,
  },

  /*
   * Vendored shadcn/ui primitives: these files are generated by the
   * shadcn CLI and live in src/components/ui/. They follow shadcn's own
   * conventions, which occasionally conflict with our strict a11y rules
   * around convenience click-to-focus patterns on grouping wrappers.
   * Override here is narrow: only the specific rules that trip on
   * shadcn's patterns, not a blanket disable.
   *
   * Why: our rule of thumb is "no eslint suppressions without a why."
   * The why here is that these are vendored primitives we adopt as-is
   * to preserve upgrade path via the shadcn CLI. We accept their a11y
   * conventions (all shadcn primitives wrap keyboard-native controls).
   */
  {
    files: ['src/components/ui/**/*.{ts,tsx}'],
    rules: {
      'jsx-a11y/click-events-have-key-events': 'off',
      'jsx-a11y/no-noninteractive-element-interactions': 'off',
    },
  },

  /*
   * Warn when user-facing strings live in JSX. Every user-facing string
   * should be sourced from src/messages/es-GT.json (S-0.8 acceptance
   * criterion). Kept as a warning rather than an error so it surfaces
   * without blocking dev loops; promote to error once Phase 2 stabilizes.
   *
   * Exemptions:
   *  - src/components/ui/**     : vendored shadcn primitives
   *  - src/app/design-system/** : dev-only visual smoke test page
   *  - src/components/branding/**, src/lib/branding/** : brand lockup
   *    text ("IFA", wordmark) is branding data, not localized copy
   *  - src/app/icon.tsx, apple-icon.tsx, opengraph-image.tsx : branded
   *    static image generators; the wordmark/tagline live in code per
   *    next/og conventions
   */
  {
    files: ['src/**/*.{ts,tsx}'],
    ignores: [
      'src/components/ui/**',
      'src/app/design-system/**',
      'src/components/branding/**',
      'src/lib/branding/**',
      'src/app/icon.tsx',
      'src/app/apple-icon.tsx',
      'src/app/opengraph-image.tsx',
    ],
    rules: {
      'react/jsx-no-literals': [
        'warn',
        {
          noStrings: true,
          ignoreProps: true,
          /*
           * Punctuation and separators that are universal and never translated
           * are allowed to live inline in JSX. Any prose or label must come
           * from src/messages/es-GT.json.
           */
          allowedStrings: ['·', '—', '→', '{', '}', ' ', '\u00A0', ':', '.', ','],
        },
      ],
    },
  },
);
